# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = FP_MVE, baseAddress = 0xE000EF34'u32, peripheralDesc = "Floating-point and MVE Extension")
declareRegister(peripheralName = FP_MVE, registerName = FPCCR, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Holds control data for the Floating Point Unit")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = ASPEN, bitOffset = 31, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Automatic state preservation enable")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = LSPEN, bitOffset = 30, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Automatic state preservation enable")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = LSPENS, bitOffset = 29, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Lazy state preservation enable Secure only")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = CLRONRET, bitOffset = 28, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Clear on return")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = CLRONRETS, bitOffset = 27, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Clear on return Secure only")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = TS, bitOffset = 26, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Treat as Secure")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = UFRDY, bitOffset = 10, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "UsageFault ready")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = SPLIMVIOL, bitOffset = 9, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Stack pointer limit violation")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = MONRDY, bitOffset = 8, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "DebugMonitor ready")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = SFRDY, bitOffset = 7, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "SecureFault ready")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = BFRDY, bitOffset = 6, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "BusFault ready")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = MMRDY, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "MemManage ready")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = HFRDY, bitOffset = 4, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "HardFault ready")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = THREAD, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Thread mode")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = S, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Security status of the floating point context")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = USER, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates the privilege level of the software executing, when the processor allocated the floating point stack")
declareField(peripheralName = FP_MVE, registerName = FPCCR, fieldName = LSPACT, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Lazy state preservation active")
declareRegister(peripheralName = FP_MVE, registerName = FPCAR, addressOffset = 0x4'u32, readAccess = true, writeAccess = true, registerDesc = "Holds the location of the unpopulated floating-point register space allocated on an exception stack frame")
declareRegister(peripheralName = FP_MVE, registerName = FPDSCR, addressOffset = 0x8'u32, readAccess = true, writeAccess = true, registerDesc = "Holds the default values for the floating-point status control data that the processor assigns to the FPSCR when it creates a new floating-point context")
declareField(peripheralName = FP_MVE, registerName = FPDSCR, fieldName = AHP, bitOffset = 26, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Default value for FPSCR.AHP")
declareField(peripheralName = FP_MVE, registerName = FPDSCR, fieldName = DN, bitOffset = 25, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Default value for FPSCR.DN")
declareField(peripheralName = FP_MVE, registerName = FPDSCR, fieldName = FZ, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Default value for FPSCR.FZ")
declareField(peripheralName = FP_MVE, registerName = FPDSCR, fieldName = RMode, bitOffset = 22, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Default value for FPSCR.RMode")
declareField(peripheralName = FP_MVE, registerName = FPDSCR, fieldName = FZ16, bitOffset = 19, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Default value for FPSCR.FZ16")
declareField(peripheralName = FP_MVE, registerName = FPDSCR, fieldName = LTPSIZE, bitOffset = 16, bitWidth = 3, readAccess = true, writeAccess = true, fieldDesc = "Default value for FPSCR.LTPSIZE")
declareRegister(peripheralName = FP_MVE, registerName = MVFR0, addressOffset = 0xC'u32, readAccess = true, writeAccess = false, registerDesc = "Describes the features provided by the Floating-point extension")
declareField(peripheralName = FP_MVE, registerName = MVFR0, fieldName = FPRound, bitOffset = 28, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point rounding modes")
declareField(peripheralName = FP_MVE, registerName = MVFR0, fieldName = FPSqrt, bitOffset = 20, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point square root")
declareField(peripheralName = FP_MVE, registerName = MVFR0, fieldName = FPDivide, bitOffset = 16, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point divide")
declareField(peripheralName = FP_MVE, registerName = MVFR0, fieldName = FPDP, bitOffset = 8, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point double-precision")
declareField(peripheralName = FP_MVE, registerName = MVFR0, fieldName = FPSP, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point single-precision")
declareField(peripheralName = FP_MVE, registerName = MVFR0, fieldName = SIMDReg, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "SIMD registers")
declareRegister(peripheralName = FP_MVE, registerName = MVFR1, addressOffset = 0x10'u32, readAccess = true, writeAccess = false, registerDesc = "Describes the features provided by the Floating-point extension")
declareField(peripheralName = FP_MVE, registerName = MVFR1, fieldName = FMAC, bitOffset = 28, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Fused multiply accumulate instructions")
declareField(peripheralName = FP_MVE, registerName = MVFR1, fieldName = FPHP, bitOffset = 24, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point half-precision conversion")
declareField(peripheralName = FP_MVE, registerName = MVFR1, fieldName = FP16, bitOffset = 20, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point half-precision data processing")
declareField(peripheralName = FP_MVE, registerName = MVFR1, fieldName = MVE, bitOffset = 8, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Indicates support for MVE")
declareField(peripheralName = FP_MVE, registerName = MVFR1, fieldName = FPDNaN, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point default NaN")
declareField(peripheralName = FP_MVE, registerName = MVFR1, fieldName = FPFtZ, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point flush-to-zero")
declareRegister(peripheralName = FP_MVE, registerName = MVFR2, addressOffset = 0x14'u32, readAccess = true, writeAccess = false, registerDesc = "Describes the features provided by the floating-point extension")
declareField(peripheralName = FP_MVE, registerName = MVFR2, fieldName = FPMisc, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point miscellaneous")
