# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = ERRBNK, baseAddress = 0xE001E100'u32, peripheralDesc = "Implementation defined error banking")
declareRegister(peripheralName = ERRBNK, registerName = IEBR1, addressOffset = 0x4'u32, readAccess = true, writeAccess = true, registerDesc = "Record errors that occur during memory accesses to the L1 instruction cache")
declareField(peripheralName = ERRBNK, registerName = IEBR1, fieldName = SWDEF, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Error detection logic sets this field to 0b00 on a new allocation and on Cold reset")
declareField(peripheralName = ERRBNK, registerName = IEBR1, fieldName = BANK, bitOffset = 16, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates which RAM bank to use")
declareField(peripheralName = ERRBNK, registerName = IEBR1, fieldName = LOCATION.WAY, bitOffset = 15, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates the location in the L1 instruction cache RAM, way")
declareField(peripheralName = ERRBNK, registerName = IEBR1, fieldName = LOCATION.INDEX, bitOffset = 5, bitWidth = 10, readAccess = true, writeAccess = true, fieldDesc = "Indicates the location in the L1 instruction cache RAM, index")
declareField(peripheralName = ERRBNK, registerName = IEBR1, fieldName = LOCATION.LWO, bitOffset = 2, bitWidth = 3, readAccess = true, writeAccess = true, fieldDesc = "Indicates the location in the L1 instruction cache RAM, line word offset")
declareField(peripheralName = ERRBNK, registerName = IEBR1, fieldName = LOCKED, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the location is locked or not")
declareField(peripheralName = ERRBNK, registerName = IEBR1, fieldName = VALID, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the entry is valid or not")
declareRegister(peripheralName = ERRBNK, registerName = DEBR1, addressOffset = 0x14'u32, readAccess = true, writeAccess = true, registerDesc = "Record errors that occur during memory accesses to the L1 data cache")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = SWDEF, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Error detection logic sets this field to 0b00 on a new allocation and on Cold reset")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = TYPE, bitOffset = 17, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates the error type")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = BANK, bitOffset = 16, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates which RAM bank to use")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = LOCATION.WAY, bitOffset = 14, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Indicates the location in the L1 instruction cache RAM, way")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = LOCATION.INDEX, bitOffset = 5, bitWidth = 9, readAccess = true, writeAccess = true, fieldDesc = "Indicates the location in the L1 instruction cache RAM, index")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = LOCATION.LWO, bitOffset = 2, bitWidth = 3, readAccess = true, writeAccess = true, fieldDesc = "Indicates the location in the L1 instruction cache RAM, line doubleword offset")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = LOCKED, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the location is locked or not")
declareField(peripheralName = ERRBNK, registerName = DEBR1, fieldName = VALID, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the entry is valid or not")
declareRegister(peripheralName = ERRBNK, registerName = TEBR0, addressOffset = 0x20'u32, readAccess = true, writeAccess = true, registerDesc = "Record the location of errors in the TCM")
declareField(peripheralName = ERRBNK, registerName = TEBR0, fieldName = SWDEF, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Error detection logic sets this field to 0b00 on a new allocation and on Cold reset")
declareField(peripheralName = ERRBNK, registerName = TEBR0, fieldName = POISON, bitOffset = 28, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether a BusFault is generated or not")
declareField(peripheralName = ERRBNK, registerName = TEBR0, fieldName = TYPE, bitOffset = 27, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates the error type")
declareField(peripheralName = ERRBNK, registerName = TEBR0, fieldName = BANK, bitOffset = 24, bitWidth = 3, readAccess = true, writeAccess = true, fieldDesc = "Indicates which RAM bank to use")
declareField(peripheralName = ERRBNK, registerName = TEBR0, fieldName = LOCATION, bitOffset = 2, bitWidth = 22, readAccess = true, writeAccess = true, fieldDesc = "Indicates the physical location in the data cache RAM")
declareField(peripheralName = ERRBNK, registerName = TEBR0, fieldName = LOCKED, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the location is locked or not")
declareField(peripheralName = ERRBNK, registerName = TEBR0, fieldName = VALID, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the entry is valid or not")
declareRegister(peripheralName = ERRBNK, registerName = TEBRDATA0, addressOffset = 0x24'u32, readAccess = true, writeAccess = false, registerDesc = "Provides storage for corrected data that is associated with an error")
declareRegister(peripheralName = ERRBNK, registerName = TEBR1, addressOffset = 0x28'u32, readAccess = true, writeAccess = true, registerDesc = "Record the location of errors in the TCM")
declareField(peripheralName = ERRBNK, registerName = TEBR1, fieldName = SWDEF, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Error detection logic sets this field to 0b00 on a new allocation and on Cold reset")
declareField(peripheralName = ERRBNK, registerName = TEBR1, fieldName = POISON, bitOffset = 28, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether a BusFault is generated or not")
declareField(peripheralName = ERRBNK, registerName = TEBR1, fieldName = TYPE, bitOffset = 27, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates the error type")
declareField(peripheralName = ERRBNK, registerName = TEBR1, fieldName = BANK, bitOffset = 24, bitWidth = 3, readAccess = true, writeAccess = true, fieldDesc = "Indicates which RAM bank to use")
declareField(peripheralName = ERRBNK, registerName = TEBR1, fieldName = LOCATION, bitOffset = 2, bitWidth = 22, readAccess = true, writeAccess = true, fieldDesc = "Indicates the physical location in the data cache RAM")
declareField(peripheralName = ERRBNK, registerName = TEBR1, fieldName = LOCKED, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the location is locked or not")
declareField(peripheralName = ERRBNK, registerName = TEBR1, fieldName = VALID, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the entry is valid or not")
declareRegister(peripheralName = ERRBNK, registerName = TEBRDATA1, addressOffset = 0x2C'u32, readAccess = true, writeAccess = false, registerDesc = "Provides storage for corrected data that is associated with an error")
