# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = MPU, baseAddress = 0xE000ED90'u32, peripheralDesc = "Memory Protection Unit")
declareRegister(peripheralName = MPU, registerName = MPU_TYPE, addressOffset = 0x0'u32, readAccess = true, writeAccess = false, registerDesc = "Indicates whether the MPU is present, and if so, how many regions it supports")
declareField(peripheralName = MPU, registerName = MPU_TYPE, fieldName = DREGION, bitOffset = 8, bitWidth = 8, readAccess = true, writeAccess = false, fieldDesc = "Number of regions supported by the MPU")
declareField(peripheralName = MPU, registerName = MPU_TYPE, fieldName = SEPARATE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Indicates support for unified or separate instructions and data address regions")
declareRegister(peripheralName = MPU, registerName = MPU_CTRL, addressOffset = 0x4'u32, readAccess = true, writeAccess = true, registerDesc = "Enables the MPU")
declareField(peripheralName = MPU, registerName = MPU_CTRL, fieldName = PRIVDEFENA, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enables privileged software access to the default memory map")
declareField(peripheralName = MPU, registerName = MPU_CTRL, fieldName = HFNMIENA, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enables the operation of MPU during HardFault and NMI handlers")
declareField(peripheralName = MPU, registerName = MPU_CTRL, fieldName = ENABLE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enables the MPU")
declareRegister(peripheralName = MPU, registerName = MPU_RNR, addressOffset = 0x8'u32, readAccess = true, writeAccess = true, registerDesc = "Selects the region currently accessed by MPU_RBAR and MPU_RLAR")
declareField(peripheralName = MPU, registerName = MPU_RNR, fieldName = REGION, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Indicates the memory region accessed by MPU_RBAR and PMU_RLAR")
declareRegister(peripheralName = MPU, registerName = MPU_RBAR, addressOffset = 0xC'u32, readAccess = true, writeAccess = true, registerDesc = "Defines the base address of the MPU region selected by the MPU_RNR")
declareField(peripheralName = MPU, registerName = MPU_RBAR, fieldName = BASE, bitOffset = 5, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Contains bits[31:5] of the lower inclusive limit of the selected MPU memory region. This value is zero extended to provide the base address to be checked against.")
declareField(peripheralName = MPU, registerName = MPU_RBAR, fieldName = SH, bitOffset = 3, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Defines the shareability domain of this region for Normal memory")
declareField(peripheralName = MPU, registerName = MPU_RBAR, fieldName = AP, bitOffset = 1, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Access permissions")
declareField(peripheralName = MPU, registerName = MPU_RBAR, fieldName = XN, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Defines whether code can be executed from this region")
declareRegister(peripheralName = MPU, registerName = MPU_RBAR_A1, addressOffset = 0x14'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the MPU base address register")
declareRegister(peripheralName = MPU, registerName = MPU_RBAR_A2, addressOffset = 0x18'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the MPU base address register")
declareRegister(peripheralName = MPU, registerName = MPU_RBAR_A3, addressOffset = 0x1C'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the MPU base address register")
declareRegister(peripheralName = MPU, registerName = MPU_RLAR, addressOffset = 0x10'u32, readAccess = true, writeAccess = true, registerDesc = "Defines the limit address of the MPU region selected by the MPU_RNR")
declareField(peripheralName = MPU, registerName = MPU_RLAR, fieldName = LIMIT, bitOffset = 5, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Contains bits[31:5] of the upper inclusive limit of the selected MPU memory region. This value is postfixed with 0x1F to provide the limit address to be checked against.")
declareField(peripheralName = MPU, registerName = MPU_RLAR, fieldName = PXN, bitOffset = 4, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Defines whether code can be executed from this privileged region")
declareField(peripheralName = MPU, registerName = MPU_RLAR, fieldName = AttrIndx, bitOffset = 1, bitWidth = 3, readAccess = true, writeAccess = true, fieldDesc = "Associates a set of attributes in the MPU_MAIR0 and MPU_MAIR1 fields")
declareField(peripheralName = MPU, registerName = MPU_RLAR, fieldName = EN, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Region enable")
declareRegister(peripheralName = MPU, registerName = MPU_RLAR_A1, addressOffset = 0x20'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the MPU limit address register")
declareRegister(peripheralName = MPU, registerName = MPU_RLAR_A2, addressOffset = 0x24'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the MPU limit address register")
declareRegister(peripheralName = MPU, registerName = MPU_RLAR_A3, addressOffset = 0x28'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the MPU limit address register")
declareRegister(peripheralName = MPU, registerName = MPU_MAIR0, addressOffset = 0x30'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the memory attribute encodings corresponding to the AttrIndex values")
declareField(peripheralName = MPU, registerName = MPU_MAIR0, fieldName = Attr3, bitOffset = 24, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 3")
declareField(peripheralName = MPU, registerName = MPU_MAIR0, fieldName = Attr2, bitOffset = 16, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 2")
declareField(peripheralName = MPU, registerName = MPU_MAIR0, fieldName = Attr1, bitOffset = 8, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 1")
declareField(peripheralName = MPU, registerName = MPU_MAIR0, fieldName = Attr0, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 0")
declareRegister(peripheralName = MPU, registerName = MPU_MAIR1, addressOffset = 0x34'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the memory attribute encodings corresponding to the AttrIndex values")
declareField(peripheralName = MPU, registerName = MPU_MAIR1, fieldName = Attr7, bitOffset = 24, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 7")
declareField(peripheralName = MPU, registerName = MPU_MAIR1, fieldName = Attr6, bitOffset = 16, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 6")
declareField(peripheralName = MPU, registerName = MPU_MAIR1, fieldName = Attr5, bitOffset = 8, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 5")
declareField(peripheralName = MPU, registerName = MPU_MAIR1, fieldName = Attr4, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Memory attribute encoding for MPU regions with an AttrIndex of 4")
