# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = TCM SecGate, baseAddress = 0xE001E500'u32, peripheralDesc = "TCM Security Gate")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_CTRL, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Main TCM Gate Unit (TGU) control registers for the ITCM")
declareField(peripheralName = TCM SecGate, registerName = ITGU_CTRL, fieldName = DEREN, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable Slave AHB (S-AHB) error response for TGU fault")
declareField(peripheralName = TCM SecGate, registerName = ITGU_CTRL, fieldName = DBFEN, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable data side BusFault for TGU fault")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_CFG, addressOffset = 0x4'u32, readAccess = true, writeAccess = false, registerDesc = "Provides access to configuration values for the ITGU")
declareField(peripheralName = TCM SecGate, registerName = ITGU_CFG, fieldName = PRESENT, bitOffset = 31, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Determines if the TGU is present")
declareField(peripheralName = TCM SecGate, registerName = ITGU_CFG, fieldName = NUMBLKS, bitOffset = 8, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "This value is used to calculate the number of TCM blocks")
declareField(peripheralName = TCM SecGate, registerName = ITGU_CFG, fieldName = BLKSZ, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "TGU block size in bytes")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT0, addressOffset = 0x00000010'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT1, addressOffset = 0x00000014'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT2, addressOffset = 0x00000018'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT3, addressOffset = 0x0000001C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT4, addressOffset = 0x00000020'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT5, addressOffset = 0x00000024'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT6, addressOffset = 0x00000028'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT7, addressOffset = 0x0000002C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT8, addressOffset = 0x00000030'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT9, addressOffset = 0x00000034'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT10, addressOffset = 0x00000038'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT11, addressOffset = 0x0000003C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT12, addressOffset = 0x00000040'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT13, addressOffset = 0x00000044'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT14, addressOffset = 0x00000048'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = ITGU_LUT15, addressOffset = 0x0000004C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the ITGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_CTRL, addressOffset = 0x100'u32, readAccess = true, writeAccess = true, registerDesc = "Main TCM Gate Unit (TGU) control registers for the DTCM")
declareField(peripheralName = TCM SecGate, registerName = DTGU_CTRL, fieldName = DEREN, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable Slave AHB (S-AHB) error response for TGU fault")
declareField(peripheralName = TCM SecGate, registerName = DTGU_CTRL, fieldName = DBFEN, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable data side BusFault for TGU fault")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_CFG, addressOffset = 0x104'u32, readAccess = true, writeAccess = false, registerDesc = "Provides access to configuration values for the DTGU")
declareField(peripheralName = TCM SecGate, registerName = DTGU_CFG, fieldName = PRESENT, bitOffset = 31, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Determines if the TGU is present")
declareField(peripheralName = TCM SecGate, registerName = DTGU_CFG, fieldName = NUMBLKS, bitOffset = 8, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "This value is used to calculate the number of TCM blocks")
declareField(peripheralName = TCM SecGate, registerName = DTGU_CFG, fieldName = BLKSZ, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "TGU block size in bytes")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT0, addressOffset = 0x00000110'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT1, addressOffset = 0x00000114'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT2, addressOffset = 0x00000118'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT3, addressOffset = 0x0000011C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT4, addressOffset = 0x00000120'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT5, addressOffset = 0x00000124'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT6, addressOffset = 0x00000128'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT7, addressOffset = 0x0000012C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT8, addressOffset = 0x00000130'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT9, addressOffset = 0x00000134'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT10, addressOffset = 0x00000138'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT11, addressOffset = 0x0000013C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT12, addressOffset = 0x00000140'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT13, addressOffset = 0x00000144'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT14, addressOffset = 0x00000148'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
declareRegister(peripheralName = TCM SecGate, registerName = DTGU_LUT15, addressOffset = 0x0000014C'u32, readAccess = true, writeAccess = true, registerDesc = "Identifying the DTGU blocks as being Secure or Non-secure")
