# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = BPU, baseAddress = 0xE0002000'u32, peripheralDesc = "Breakpoint Unit")
declareRegister(peripheralName = BPU, registerName = BP_CTRL, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Provides BPU implementation information, and the global enable for the BPU")
declareField(peripheralName = BPU, registerName = BP_CTRL, fieldName = NUM_CODE, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "The number of breakpoint comparators")
declareField(peripheralName = BPU, registerName = BP_CTRL, fieldName = KEY, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "On any write to FP_CTRL, this bit must be 1")
declareField(peripheralName = BPU, registerName = BP_CTRL, fieldName = ENABLE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable bit for the FPB")
declareRegister(peripheralName = BPU, registerName = BP_COMP_0, addressOffset = 0x00000008'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_0, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_0, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_0, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
declareRegister(peripheralName = BPU, registerName = BP_COMP_1, addressOffset = 0x0000000C'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_1, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_1, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_1, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
declareRegister(peripheralName = BPU, registerName = BP_COMP_2, addressOffset = 0x00000010'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_2, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_2, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_2, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
declareRegister(peripheralName = BPU, registerName = BP_COMP_3, addressOffset = 0x00000014'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_3, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_3, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_3, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
declareRegister(peripheralName = BPU, registerName = BP_COMP_4, addressOffset = 0x00000018'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_4, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_4, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_4, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
declareRegister(peripheralName = BPU, registerName = BP_COMP_5, addressOffset = 0x0000001C'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_5, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_5, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_5, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
declareRegister(peripheralName = BPU, registerName = BP_COMP_6, addressOffset = 0x00000020'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_6, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_6, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_6, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
declareRegister(peripheralName = BPU, registerName = BP_COMP_7, addressOffset = 0x00000024'u32, readAccess = true, writeAccess = true, registerDesc = "Holds a breakpoint address for comparison with instruction addresses in the Code memory region")
declareField(peripheralName = BPU, registerName = BP_COMP_7, fieldName = BP_MATCH, bitOffset = 30, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "defines the behavior when the COMP address is matched")
declareField(peripheralName = BPU, registerName = BP_COMP_7, fieldName = COMP, bitOffset = 2, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Stores bits [28:2] of the comparison address")
declareField(peripheralName = BPU, registerName = BP_COMP_7, fieldName = BE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "enables the comperator")
