# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = DWT, baseAddress = 0xE0001000'u32, peripheralDesc = "Data Watchpoint and Trace")
declareRegister(peripheralName = DWT, registerName = DWT_CTRL, addressOffset = 0x0'u32, readAccess = true, writeAccess = false, registerDesc = "Provides configuration and status information for the DWT unit, and used to control features of the unit")
declareField(peripheralName = DWT, registerName = DWT_CTRL, fieldName = NUMCOMP, bitOffset = 28, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Number of comparators implemented")
declareRegister(peripheralName = DWT, registerName = DWT_PCSR, addressOffset = 0x1C'u32, readAccess = true, writeAccess = false, registerDesc = "Samples the current value of the program counter")
declareField(peripheralName = DWT, registerName = DWT_PCSR, fieldName = EIASAMPLE, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = false, fieldDesc = "Executed Instruction Address sample value")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_0, addressOffset = 0x00000020'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_0, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_1, addressOffset = 0x00000024'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_1, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_2, addressOffset = 0x00000028'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_2, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_3, addressOffset = 0x0000002C'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_3, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_4, addressOffset = 0x00000030'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_4, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_5, addressOffset = 0x00000034'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_5, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_6, addressOffset = 0x00000038'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_6, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_COMP_7, addressOffset = 0x0000003C'u32, readAccess = true, writeAccess = true, registerDesc = "Provides a reference value for use by comparator n")
declareField(peripheralName = DWT, registerName = DWT_COMP_7, fieldName = COMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Reference value for comparison")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_0, addressOffset = 0x00000024'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_0, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_1, addressOffset = 0x00000028'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_1, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_2, addressOffset = 0x0000002C'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_2, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_3, addressOffset = 0x00000030'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_3, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_4, addressOffset = 0x00000034'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_4, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_5, addressOffset = 0x00000038'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_5, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_6, addressOffset = 0x0000003C'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_6, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_MASK_7, addressOffset = 0x00000040'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the size of the ignore mask applied to the access address for address range matching by comparator n")
declareField(peripheralName = DWT, registerName = DWT_MASK_7, fieldName = MASK, bitOffset = 0, bitWidth = 5, readAccess = true, writeAccess = true, fieldDesc = "The size of the ignore mask, 0-31 bits, applied to address range matching")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_0, addressOffset = 0x00000028'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_0, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_0, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_1, addressOffset = 0x0000002C'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_1, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_1, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_2, addressOffset = 0x00000030'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_2, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_2, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_3, addressOffset = 0x00000034'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_3, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_3, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_4, addressOffset = 0x00000038'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_4, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_4, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_5, addressOffset = 0x0000003C'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_5, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_5, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_6, addressOffset = 0x00000040'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_6, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_6, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
declareRegister(peripheralName = DWT, registerName = DWT_FUNCTION_7, addressOffset = 0x00000044'u32, readAccess = true, writeAccess = true, registerDesc = "Controls the operation of comparator n")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_7, fieldName = MATCHED, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Comparator match")
declareField(peripheralName = DWT, registerName = DWT_FUNCTION_7, fieldName = FUNCTION, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = true, fieldDesc = "Selects action taken on comparator match")
