# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = DCB, baseAddress = 0xE000EDF0'u32, peripheralDesc = "Debug Control Block")
declareRegister(peripheralName = DCB, registerName = DHCSR, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Controls halting debug")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = DBGKEY, bitOffset = 16, bitWidth = 16, readAccess = true, writeAccess = true, fieldDesc = "Debug key")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_RESET_ST, bitOffset = 25, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the processor has been reset since the last read of DHCSR")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_RETIRE_ST, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Set to 1 every time the processor retires one or more instructions")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_LOCKUP, bitOffset = 19, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the processor is locked up because of an unrecoverable exception")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_SLEEP, bitOffset = 18, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the processor is sleeping")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_HALT, bitOffset = 17, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the processor is in Debug state")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_REGRDY, bitOffset = 16, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "A handshake flag for transfers through the DCRDR")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_SNAPSTALL, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Allow imprecise entry to Debug state")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_MASKINTS, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "When debug is enabled, the debugger can write to this bit to mask PendSV, SysTick and external configurable interrupts")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_STEP, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Processor step bit")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_HALT, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Processor halt bit")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_DEBUGEN, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Halting debug enable bit")
declareRegister(peripheralName = DCB, registerName = DCRSR, addressOffset = 0x4'u32, readAccess = false, writeAccess = true, registerDesc = "provides debug access to the ARM core registers, special-purpose registers, and Floating-point extension regi")
declareField(peripheralName = DCB, registerName = DCRSR, fieldName = REGWnR, bitOffset = 16, bitWidth = 1, readAccess = false, writeAccess = true, fieldDesc = "Specifies the access type for the transfer")
declareField(peripheralName = DCB, registerName = DCRSR, fieldName = REGSEL, bitOffset = 0, bitWidth = 7, readAccess = false, writeAccess = true, fieldDesc = "Specifies the ARM core register, special-purpose register, or Floating-point extension register, to transfer")
declareRegister(peripheralName = DCB, registerName = DCRDR, addressOffset = 0x8'u32, readAccess = true, writeAccess = true, registerDesc = "provides debug access to the ARM core registers, special-purpose registers, and Floating-point extensio")
declareField(peripheralName = DCB, registerName = DCRDR, fieldName = DBGTMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Data temporary cache, for reading and writing the ARM core registers, special-purpose registers, and Floating-point extension registers")
declareRegister(peripheralName = DCB, registerName = DEMCR, addressOffset = 0xC'u32, readAccess = true, writeAccess = true, registerDesc = "Manages vector catch behavior and DebugMonitor handling when debugging")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = TRCENA, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Global enable for all DWT and ITM features")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_REQ, bitOffset = 19, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "DebugMonitor semaphore bit")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_STEP, bitOffset = 18, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "When MON_EN is set to 0, this feature is disabled and the processor ignores MON_STEP")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_PEND, bitOffset = 17, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Sets or clears the pending state of the DebugMonitor exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_EN, bitOffset = 16, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable the DebugMonitor exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_HARDERR, bitOffset = 10, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable halting debug trap on a HardFault exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_INTERR, bitOffset = 9, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable halting debug trap on a fault occurring during exception entry or exception return")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_BUSERR, bitOffset = 8, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable halting debug trap on a BusFault exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_STATERR, bitOffset = 7, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable halting debug trap on a UsageFault exception caused by a state information error, for example an Undefined Instruction exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_CHKERR, bitOffset = 6, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable halting debug trap on a UsageFault exception caused by a checking error, for example an alignment check error")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_NOCPERR, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable halting debug trap on a UsageFault caused by an access to a Coprocessor")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_MMERR, bitOffset = 4, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable halting debug trap on a MemManage exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_CORERESET, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enable Reset Vector Catch")
