# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = DCB, baseAddress = 0xE000EDF0'u32, peripheralDesc = "Debug Control Block")
declareRegister(peripheralName = DCB, registerName = DAUTHCTRL, addressOffset = 0x14'u32, readAccess = true, writeAccess = true, registerDesc = "This register allows the IMPLEMENTATION DEFINED authentication interface to be overridden from software")
declareField(peripheralName = DCB, registerName = DAUTHCTRL, fieldName = INTSPNIDEN, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Internal Secure non-invasive debug enable")
declareField(peripheralName = DCB, registerName = DAUTHCTRL, fieldName = SPNIDENSEL, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Secure non-invasive debug enable select")
declareField(peripheralName = DCB, registerName = DAUTHCTRL, fieldName = INTSPIDEN, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Internal Secure invasive debug enable")
declareField(peripheralName = DCB, registerName = DAUTHCTRL, fieldName = SPIDENSEL, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Secure invasive debug enable select")
declareRegister(peripheralName = DCB, registerName = DCRDR, addressOffset = 0x8'u32, readAccess = true, writeAccess = true, registerDesc = "provides debug access to the general-purpose registers, special-purpose registers, and the FP Extension registers")
declareField(peripheralName = DCB, registerName = DCRDR, fieldName = DBGTMP, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Data temporary buffer")
declareRegister(peripheralName = DCB, registerName = DCRSR, addressOffset = 0x4'u32, readAccess = false, writeAccess = true, registerDesc = "provides debug access to the general-purpose registers, special-purpose registers, and the FP extension registers")
declareField(peripheralName = DCB, registerName = DCRSR, fieldName = REGWnR, bitOffset = 16, bitWidth = 1, readAccess = false, writeAccess = true, fieldDesc = "Register write/not-read. Specifies the access type for the transfer")
declareField(peripheralName = DCB, registerName = DCRSR, fieldName = REGSEL, bitOffset = 0, bitWidth = 7, readAccess = false, writeAccess = true, fieldDesc = "Register selector")
declareField(peripheralName = DCB, registerName = DCRSR, fieldName = If_the_Main_Extension_is_not_implemented, bitOffset = 8, bitWidth = 16, readAccess = false, writeAccess = true, fieldDesc = "the Security Extension is not implemented, this value is reserved")
declareRegister(peripheralName = DCB, registerName = DEMCR, addressOffset = 0xC'u32, readAccess = true, writeAccess = true, registerDesc = "Manages vector catch behavior and DebugMonitor handling when debugging")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = TRCENA, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Trace enable. Global enable for all DWT and ITM features")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = SDME, bitOffset = 20, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Secure DebugMonitor enable")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_REQ, bitOffset = 19, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Monitor request. DebugMonitor semaphore bit")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_STEP, bitOffset = 18, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Monitor step. Enable DebugMonitor stepping")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_PEND, bitOffset = 17, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Monitor pend. Sets or clears the pending state of the DebugMonitor exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = MON_EN, bitOffset = 16, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Monitor enable. Enable the DebugMonitor exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_SFERR, bitOffset = 11, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch SecureFault. SecureFault exception Halting debug vector catch enable")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_HARDERR, bitOffset = 10, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch HardFault errors. HardFault exception Halting debug vector catch enable")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_INTERR, bitOffset = 9, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch interrupt errors")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_BUSERR, bitOffset = 8, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch BusFault errors. BusFault exception Halting debug vector catch enable")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_STATERR, bitOffset = 7, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch state errors")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_CHKERR, bitOffset = 6, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch check errors")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_NOCPERR, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch NOCP errors")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_MMERR, bitOffset = 4, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch MemManage errors. Enable Halting debug trap on a MemManage exception")
declareField(peripheralName = DCB, registerName = DEMCR, fieldName = VC_CORERESET, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Vector Catch core reset. Enable Reset Vector Catch")
declareRegister(peripheralName = DCB, registerName = DHCSR, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Controls Halting debug")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = DBGKEY, bitOffset = 16, bitWidth = 16, readAccess = true, writeAccess = true, fieldDesc = "Debug key")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_RESTART_ST, bitOffset = 26, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Restart sticky status. Indicates the PE has processed a request to clear DHCSR.C_HALT to 0")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_RESET_ST, bitOffset = 25, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Reset sticky status. Indicates whether the PE has been reset since the last read of the DHCSR")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_RETIRE_ST, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Retire sticky status. Set to 1 every time the PE retires one of more instructions")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_SDE, bitOffset = 20, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Secure debug enabled. Indicates whether Secure invasive debug is allowed")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_LOCKUP, bitOffset = 19, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Lockup status. Indicates whether the PE is in Lockup state")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_SLEEP, bitOffset = 18, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Sleeping status. Indicates whether the PE is sleeping")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_HALT, bitOffset = 17, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Halted status. Indicates whether the PE is in Debug state")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = S_REGRDY, bitOffset = 16, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Register ready status. Handshake flag to transfers through the DCRDR")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_SNAPSTALL, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Snap stall control. Allow imprecise entry to Debug state")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_MASKINTS, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Mask interrupts control")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_STEP, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Step control. Enable single instruction step")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_HALT, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Halt control. PE enter Debug state halt request")
declareField(peripheralName = DCB, registerName = DHCSR, fieldName = C_DEBUGEN, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Debug enable control. Enable Halting debug")
declareRegister(peripheralName = DCB, registerName = DSCSR, addressOffset = 0x18'u32, readAccess = true, writeAccess = true, registerDesc = "Provides control and status information for Secure debug")
declareField(peripheralName = DCB, registerName = DSCSR, fieldName = CDSKEY, bitOffset = 17, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "CDS write-enable key")
declareField(peripheralName = DCB, registerName = DSCSR, fieldName = CDS, bitOffset = 16, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Current domain Secure. This field indicates the current Security state of the processor")
declareField(peripheralName = DCB, registerName = DSCSR, fieldName = SBRSEL, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Secure Banked register select")
declareField(peripheralName = DCB, registerName = DSCSR, fieldName = SBRSELEN, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Secure Banked register select enable")
