# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = FP, baseAddress = 0xE000EF34'u32, peripheralDesc = "Floating-Point Extension")
declareRegister(peripheralName = FP, registerName = FPCAR, addressOffset = 0x4'u32, readAccess = true, writeAccess = true, registerDesc = "Holds the location of the unpopulated floating-point register space allocated on an exception stack frame")
declareField(peripheralName = FP, registerName = FPCAR, fieldName = ADDRESS, bitOffset = 3, bitWidth = 29, readAccess = true, writeAccess = true, fieldDesc = "Address")
declareRegister(peripheralName = FP, registerName = FPCCR, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Holds control data for the Floating-point extension")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = ASPEN, bitOffset = 31, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Automatic state preservation enable")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = LSPEN, bitOffset = 30, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Lazy state preservation enable. Enables lazy context save of floating-point state")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = LSPENS, bitOffset = 29, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Lazy state preservation enable Secure only")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = CLRONRET, bitOffset = 28, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Clear on return. Clear floating-point caller saved registers on exception return")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = CLRONRETS, bitOffset = 27, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Clear on return Secure only")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = TS, bitOffset = 26, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Treat as Secure. Treat floating-point registers as Secure enable")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = UFRDY, bitOffset = 10, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "UsageFault ready")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = SPLIMVIOL, bitOffset = 9, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Stack pointer limit violation")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = MONRDY, bitOffset = 8, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "DebugMonitor ready")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = SFRDY, bitOffset = 7, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "SecureFault ready")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = BFRDY, bitOffset = 6, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "BusFault ready")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = MMRDY, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "MemManage ready")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = HFRDY, bitOffset = 4, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "HardFault ready")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = THREAD, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Thread mode. Indicates the PE mode when it allocated the floating-point stack frame")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = S, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Security. Security status of the floating-point context")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = USER, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "User privilege")
declareField(peripheralName = FP, registerName = FPCCR, fieldName = LSPACT, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Lazy state preservation active")
declareRegister(peripheralName = FP, registerName = FPDSCR, addressOffset = 0x8'u32, readAccess = true, writeAccess = true, registerDesc = "Holds the default values for the floating-point status control data that the PE assigns to the FPSCR when it creates a new floating-point context")
declareField(peripheralName = FP, registerName = FPDSCR, fieldName = AHP, bitOffset = 26, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Alternative half-precision. Default value for FPSCR.AHP")
declareField(peripheralName = FP, registerName = FPDSCR, fieldName = DN, bitOffset = 25, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Default NaN. Default value for FPSCR.DN")
declareField(peripheralName = FP, registerName = FPDSCR, fieldName = FZ, bitOffset = 24, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Flush-to-zero. Default value for FPSCR.FZ")
declareField(peripheralName = FP, registerName = FPDSCR, fieldName = RMode, bitOffset = 22, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Rounding mode. Default value for FPSCR.RMode")
declareRegister(peripheralName = FP, registerName = MVFR0, addressOffset = 0xC'u32, readAccess = true, writeAccess = false, registerDesc = "Describes the features provided by the Floating-point Extension")
declareField(peripheralName = FP, registerName = MVFR0, fieldName = FPRound, bitOffset = 28, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point rounding modes. Indicates the rounding modes supported by the FP Extension")
declareField(peripheralName = FP, registerName = MVFR0, fieldName = FPSqrt, bitOffset = 20, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point square root. Indicates the support for FP square root operations")
declareField(peripheralName = FP, registerName = MVFR0, fieldName = FPDivide, bitOffset = 16, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point divide. Indicates the support for FP divide operations")
declareField(peripheralName = FP, registerName = MVFR0, fieldName = FPDP, bitOffset = 8, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point double-precision. Indicates support for FP double-precision operations")
declareField(peripheralName = FP, registerName = MVFR0, fieldName = FPSP, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point single-precision. Indicates support for FP single-precision operations")
declareField(peripheralName = FP, registerName = MVFR0, fieldName = SIMDReg, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "SIMD registers. Indicates size of FP register file")
declareRegister(peripheralName = FP, registerName = MVFR1, addressOffset = 0x10'u32, readAccess = true, writeAccess = false, registerDesc = "Describes the features provided by the Floating-point Extension")
declareField(peripheralName = FP, registerName = MVFR1, fieldName = FMAC, bitOffset = 28, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Fused multiply accumulate")
declareField(peripheralName = FP, registerName = MVFR1, fieldName = FPHP, bitOffset = 24, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point half-precision")
declareField(peripheralName = FP, registerName = MVFR1, fieldName = FPDNaN, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point default NaN")
declareField(peripheralName = FP, registerName = MVFR1, fieldName = FPFtZ, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point flush-to-zero. Indicates whether subnormals are always flushed-to-zero")
declareRegister(peripheralName = FP, registerName = MVFR2, addressOffset = 0x14'u32, readAccess = true, writeAccess = false, registerDesc = "Describes the features provided by the Floating-point Extension")
declareField(peripheralName = FP, registerName = MVFR2, fieldName = FPMisc, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Floating-point miscellaneous. Indicates support for miscellaneous FP features")
