# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = RAS Ext, baseAddress = 0xE0005000'u32, peripheralDesc = "Reliability, Availability, and Serviceability (RAS) Extension")
declareRegister(peripheralName = RAS Ext, registerName = ERRFR0, addressOffset = 0x0'u32, readAccess = true, writeAccess = false, registerDesc = "Describes the RAS features that are supported")
declareField(peripheralName = RAS Ext, registerName = ERRFR0, fieldName = UE, bitOffset = 8, bitWidth = 2, readAccess = true, writeAccess = false, fieldDesc = "Enable Uncorrected error (UE) reporting as an external abort")
declareField(peripheralName = RAS Ext, registerName = ERRFR0, fieldName = ED, bitOffset = 0, bitWidth = 2, readAccess = true, writeAccess = false, fieldDesc = "Error reporting and logging")
declareRegister(peripheralName = RAS Ext, registerName = ERRCTRL0, addressOffset = 0x8'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRSTATUS0, addressOffset = 0x10'u32, readAccess = true, writeAccess = true, registerDesc = "Contains information about the Reliability, Availability, and Serviceability (RAS) event that is currently logged in record 0")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = AV, bitOffset = 31, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Address valid")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = V, bitOffset = 30, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Status valid")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = UE, bitOffset = 29, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Uncorrected errors (UEs)")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = ER, bitOffset = 28, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "BusFault caused by RAS event")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = OF, bitOffset = 27, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "RAS events occurred since the last time ERRSTATUS0.V was cleared")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = MV, bitOffset = 26, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Miscellaneous registers valid")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = CE, bitOffset = 24, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Corrected errors")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = DE, bitOffset = 23, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Deferred errors")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = POISON, bitOffset = 22, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "BusFault due to RPOISON or TEBRn.POISON")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = UET, bitOffset = 20, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Uncorrectable error type")
declareField(peripheralName = RAS Ext, registerName = ERRSTATUS0, fieldName = SERR, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Architecturally-defined primary error code")
declareRegister(peripheralName = RAS Ext, registerName = ERRADDR20, addressOffset = 0x1C'u32, readAccess = true, writeAccess = false, registerDesc = "Contains information about the address of the Reliability, Availability, and Serviceability (RAS) event in record 0")
declareField(peripheralName = RAS Ext, registerName = ERRADDR20, fieldName = SI, bitOffset = 30, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Security information incorrect")
declareField(peripheralName = RAS Ext, registerName = ERRADDR20, fieldName = AI, bitOffset = 29, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Address incorrect")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC00, addressOffset = 0x20'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC10, addressOffset = 0x24'u32, readAccess = true, writeAccess = false, registerDesc = "Error syndrome register for the event in record 0")
declareField(peripheralName = RAS Ext, registerName = ERRMISC10, fieldName = TYPE, bitOffset = 0, bitWidth = 2, readAccess = true, writeAccess = false, fieldDesc = "type of Reliability, Availability, and Serviceability (RAS) event logged")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC20, addressOffset = 0x28'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC30, addressOffset = 0x2C'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC40, addressOffset = 0x30'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC50, addressOffset = 0x34'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC60, addressOffset = 0x38'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRMISC70, addressOffset = 0x3C'u32, readAccess = true, writeAccess = false, registerDesc = "This register is RES0")
declareRegister(peripheralName = RAS Ext, registerName = ERRGSR0, addressOffset = 0xE00'u32, readAccess = true, writeAccess = false, registerDesc = "Summarizes the valid error records")
declareField(peripheralName = RAS Ext, registerName = ERRGSR0, fieldName = ERR0, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Error record 0 is valid")
declareRegister(peripheralName = RAS Ext, registerName = ERRDEVID, addressOffset = 0xFC8'u32, readAccess = true, writeAccess = false, registerDesc = "Contains the number of error records that an implementation supports")
declareField(peripheralName = RAS Ext, registerName = ERRDEVID, fieldName = NUM, bitOffset = 0, bitWidth = 16, readAccess = true, writeAccess = false, fieldDesc = "Maximum Error Record Index+1")
declareRegister(peripheralName = RAS Ext, registerName = RFSR, addressOffset = 0x9F04'u32, readAccess = true, writeAccess = true, registerDesc = "Reports the fault status of Reliability, Availability, and Serviceability (RAS) related faults from Error Correcting Code (ECC) errors that are detected in the Level 1 (L1) instruction cache, data cache, and TCM")
declareField(peripheralName = RAS Ext, registerName = RFSR, fieldName = Valid, bitOffset = 31, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates whether the register is valid")
declareField(peripheralName = RAS Ext, registerName = RFSR, fieldName = IS, bitOffset = 16, bitWidth = 15, readAccess = true, writeAccess = true, fieldDesc = "Indicates the type of RAS exception that has occurred")
declareField(peripheralName = RAS Ext, registerName = RFSR, fieldName = UET, bitOffset = 0, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Error type")
