# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = SAU, baseAddress = 0xE000EDD0'u32, peripheralDesc = "Security Attribution Unit")
declareRegister(peripheralName = SAU, registerName = SAU_CTRL, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Allows enabling of the Security Attribution Unit (SAU)")
declareField(peripheralName = SAU, registerName = SAU_CTRL, fieldName = ALLNS, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "When SAU_CTRL.ENABLE is 0 this bit controls whether the memory is marked as Non-secure or Secure")
declareField(peripheralName = SAU, registerName = SAU_CTRL, fieldName = ENABLE, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Enables the (SAU)")
declareRegister(peripheralName = SAU, registerName = SAU_TYPE, addressOffset = 0x4'u32, readAccess = true, writeAccess = false, registerDesc = "Indicates the number of regions implemented by the Security Attribution Unit (SAU)")
declareField(peripheralName = SAU, registerName = SAU_TYPE, fieldName = SREGION, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = false, fieldDesc = "The number of implemented (SAU) regions")
declareRegister(peripheralName = SAU, registerName = SAU_RNR, addressOffset = 0x8'u32, readAccess = true, writeAccess = true, registerDesc = "Selects the region currently accessed by SAU_RBAR and SAU_RLAR")
declareField(peripheralName = SAU, registerName = SAU_RNR, fieldName = REGION, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = true, fieldDesc = "Indicates the Security Attribution Unit (SAU) region accessed by SAU_RBAR and SAU_RLAR")
declareRegister(peripheralName = SAU, registerName = SAU_RBAR, addressOffset = 0xC'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the base address of the currently selected Security Attribution Unit (SAU) region")
declareField(peripheralName = SAU, registerName = SAU_RBAR, fieldName = BADDR, bitOffset = 5, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Holds bits[31:5] of the base address for the selected (SAU) region")
declareRegister(peripheralName = SAU, registerName = SAU_RLAR, addressOffset = 0x10'u32, readAccess = true, writeAccess = true, registerDesc = "Provides indirect read and write access to the limit address of the currently selected Security Attribution Unit (SAU) region")
declareField(peripheralName = SAU, registerName = SAU_RLAR, fieldName = LADDR, bitOffset = 5, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Holds bits[31:5] of the limit address for the selected (SAU) region")
declareField(peripheralName = SAU, registerName = SAU_RLAR, fieldName = NSC, bitOffset = 5, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "Controls whether Non-secure state is permitted to execute an SG instruction from this region")
declareField(peripheralName = SAU, registerName = SAU_RLAR, fieldName = ENABLE, bitOffset = 5, bitWidth = 27, readAccess = true, writeAccess = true, fieldDesc = "(SAU) region enable")
declareRegister(peripheralName = SAU, registerName = SFSR, addressOffset = 0x14'u32, readAccess = true, writeAccess = true, registerDesc = "Provides information about any security related faults")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = LSERR, bitOffset = 7, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Sticky flag indicating that an error occurred during lazy state activation or deactivation")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = SFARVALID, bitOffset = 6, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "This bit is set when the SFAR register contains a valid value")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = LSPERR, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Sticky flag indicating that an Security Attribution Unit (SAU) or Implementation Defined Attribution Unit (IDAU) violation occurred during the lazy preservation of floating-point state")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = INVTRAN, bitOffset = 4, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Sticky flag indicating that an exception was raised due to a branch that was not flagged as being domain crossing causing a transition from Secure to Non-secure memory")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = AUVIOL, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Sticky flag indicating that an attempt was made to access parts of the address space that are marked as Secure with NS-Req for the transaction set to Non-secure")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = INVER, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates EXC_RETURN.DCRS being set to 0 when returning from an exception in the Non-secure state, or EXC_RETURN.ES being set to 1 when returning from an exception in the Non-secure state")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = INVIS, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Indicates the integrity signature in an exception stack frame is found to be invalid during the unstacking operation")
declareField(peripheralName = SAU, registerName = SFSR, fieldName = INVEP, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Inidcates a function call from the Non-secure state or exception targets a non-SG instruction in the Secure state")
declareRegister(peripheralName = SAU, registerName = SFAR, addressOffset = 0x18'u32, readAccess = true, writeAccess = true, registerDesc = "Shows the address of the memory location that caused a security violation")
