# To learn how to use the output of the declarations below, visit:
# https://github.com/dwhall/minisvd2nim/blob/main/README.md#how-to-access-the-device

import metagenerator

#!fmt: off
declarePeripheral(peripheralName = ITM, baseAddress = 0xE0000000'u32, peripheralDesc = "Instrumentation Macrocell")
declareRegister(peripheralName = ITM, registerName = ITM_CIDR0, addressOffset = 0xFF0'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_CIDR0, fieldName = PRMBL_0, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = false, fieldDesc = "CoreSight component identification preamble")
declareRegister(peripheralName = ITM, registerName = ITM_CIDR1, addressOffset = 0xFF4'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_CIDR1, fieldName = CLASS, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "CoreSight component class. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_CIDR1, fieldName = PRMBL_1, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "CoreSight component identification preamble")
declareRegister(peripheralName = ITM, registerName = ITM_CIDR2, addressOffset = 0xFF8'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_CIDR2, fieldName = PRMBL_2, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = false, fieldDesc = "CoreSight component identification preamble")
declareRegister(peripheralName = ITM, registerName = ITM_CIDR3, addressOffset = 0xFFC'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_CIDR3, fieldName = PRMBL_3, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = false, fieldDesc = "CoreSight component identification preamble")
declareRegister(peripheralName = ITM, registerName = ITM_DEVARCH, addressOffset = 0xFBC'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_DEVARCH, fieldName = ARCHITECT, bitOffset = 21, bitWidth = 11, readAccess = true, writeAccess = false, fieldDesc = "Architect. Defines the architect of the component")
declareField(peripheralName = ITM, registerName = ITM_DEVARCH, fieldName = PRESENT, bitOffset = 20, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "DEVARCH Present. Defines that the DEVARCH register is present")
declareField(peripheralName = ITM, registerName = ITM_DEVARCH, fieldName = REVISION, bitOffset = 16, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Revision. Defines the architecture revision of the component")
declareField(peripheralName = ITM, registerName = ITM_DEVARCH, fieldName = ARCHVER, bitOffset = 12, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Architecture Version. Defines the architecture version of the component")
declareField(peripheralName = ITM, registerName = ITM_DEVARCH, fieldName = ARCHPART, bitOffset = 0, bitWidth = 12, readAccess = true, writeAccess = false, fieldDesc = "Architecture Part. Defines the architecture of the component")
declareRegister(peripheralName = ITM, registerName = ITM_DEVTYPE, addressOffset = 0xFCC'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_DEVTYPE, fieldName = SUB, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Subtype. Component subtype")
declareField(peripheralName = ITM, registerName = ITM_DEVTYPE, fieldName = MAJOR, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Major type. Component major type")
declareRegister(peripheralName = ITM, registerName = ITM_LAR, addressOffset = 0xFB0'u32, readAccess = false, writeAccess = true, registerDesc = "Provides CoreSight Software Lock control for the ITM, see the CoreSight Architecture Specification for details")
declareField(peripheralName = ITM, registerName = ITM_LAR, fieldName = KEY, bitOffset = 0, bitWidth = 32, readAccess = false, writeAccess = true, fieldDesc = "Lock Access control")
declareRegister(peripheralName = ITM, registerName = ITM_LSR, addressOffset = 0xFB4'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight Software Lock status information for the ITM, see the CoreSight Architecture Specification for details")
declareField(peripheralName = ITM, registerName = ITM_LSR, fieldName = nTT, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Not thirty-two bit. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_LSR, fieldName = SLK, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Software Lock status. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_LSR, fieldName = SLI, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "Software Lock implemented. See the CoreSight Architecture Specification")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR0, addressOffset = 0xFE0'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_PIDR0, fieldName = PART_0, bitOffset = 0, bitWidth = 8, readAccess = true, writeAccess = false, fieldDesc = "Part number bits [7:0]. See the CoreSight Architecture Specification")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR1, addressOffset = 0xFE4'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_PIDR1, fieldName = DES_0, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "JEP106 identification code bits [3:0]. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_PIDR1, fieldName = PART_1, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Part number bits [11:8]. See the CoreSight Architecture Specification")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR2, addressOffset = 0xFE8'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_PIDR2, fieldName = REVISION, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Component revision. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_PIDR2, fieldName = JEDEC, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = false, fieldDesc = "JEDEC assignee value is used. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_PIDR2, fieldName = DES_1, bitOffset = 0, bitWidth = 3, readAccess = true, writeAccess = false, fieldDesc = "JEP106 identification code bits [6:4]. See the CoreSight Architecture Specification")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR3, addressOffset = 0xFEC'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_PIDR3, fieldName = REVAND, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "RevAnd. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_PIDR3, fieldName = CMOD, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "Customer Modified. See the CoreSight Architecture Specification")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR4, addressOffset = 0xFD0'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareField(peripheralName = ITM, registerName = ITM_PIDR4, fieldName = SIZE, bitOffset = 4, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "4KB count. See the CoreSight Architecture Specification")
declareField(peripheralName = ITM, registerName = ITM_PIDR4, fieldName = DES_2, bitOffset = 0, bitWidth = 4, readAccess = true, writeAccess = false, fieldDesc = "JEP106 continuation code. See the CoreSight Architecture Specification")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR5, addressOffset = 0xFD4'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR6, addressOffset = 0xFD8'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareRegister(peripheralName = ITM, registerName = ITM_PIDR7, addressOffset = 0xFDC'u32, readAccess = true, writeAccess = false, registerDesc = "Provides CoreSight discovery information for the ITM")
declareRegister(peripheralName = ITM, registerName = ITM_STIM, addressOffset = 0x0'u32, readAccess = true, writeAccess = true, registerDesc = "Provides the interface for generating Instrumentation packets")
declareField(peripheralName = ITM, registerName = ITM_STIM, fieldName = STIMULUS, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus data")
declareField(peripheralName = ITM, registerName = ITM_STIM, fieldName = DISABLED, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Disabled. Indicates whether the stimulus port is enabled or disabled")
declareField(peripheralName = ITM, registerName = ITM_STIM, fieldName = FIFOREADY, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "FIFO ready. Indicates whether the stimulus port can accept data")
declareRegister(peripheralName = ITM, registerName = ITM_TCR, addressOffset = 0xE80'u32, readAccess = true, writeAccess = true, registerDesc = "Configures and controls transfers through the ITM interface")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = BUSY, bitOffset = 23, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "ITM busy. Indicates whether the ITM is currently processing events")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = TraceBusID, bitOffset = 16, bitWidth = 7, readAccess = true, writeAccess = true, fieldDesc = "Trace bus identity. Identifier for multi-source trace stream formatting")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = GTSFREQ, bitOffset = 10, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Global timestamp frequency")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = TSPrescale, bitOffset = 8, bitWidth = 2, readAccess = true, writeAccess = true, fieldDesc = "Timestamp prescale. Local timestamp prescaler, used with the trace packet reference clock")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = STALLENA, bitOffset = 5, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Stall enable. Stall the PE to guarantee delivery of Data Trace packets")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = SWOENA, bitOffset = 4, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "SWO enable. Enables asynchronous clocking of the timestamp counter")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = TXENA, bitOffset = 3, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Transmit enable")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = SYNCENA, bitOffset = 2, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Synchronization enable. Enables Synchronization packet transmission for a synchronous TPIU")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = TSENA, bitOffset = 1, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "Timestamp enable. Enables Local timestamp generation")
declareField(peripheralName = ITM, registerName = ITM_TCR, fieldName = ITMENA, bitOffset = 0, bitWidth = 1, readAccess = true, writeAccess = true, fieldDesc = "ITM enable. Enables the ITM")
declareDimRegister(peripheralName = ITM, registerName = ITM_TER, addressOffset = 0x00000E00'u32, dim = 7, dimIncrement = 4, readAccess = true, writeAccess = true, registerDesc = "Provide an individual enable bit for each ITM_STIM register")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_0, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_1, bitOffset = 1, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_2, bitOffset = 2, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_3, bitOffset = 3, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_4, bitOffset = 4, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_5, bitOffset = 5, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_6, bitOffset = 6, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_7, bitOffset = 7, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_8, bitOffset = 8, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_9, bitOffset = 9, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_10, bitOffset = 10, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_11, bitOffset = 11, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_12, bitOffset = 12, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_13, bitOffset = 13, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_14, bitOffset = 14, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_15, bitOffset = 15, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_16, bitOffset = 16, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_17, bitOffset = 17, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_18, bitOffset = 18, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_19, bitOffset = 19, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_20, bitOffset = 20, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_21, bitOffset = 21, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_22, bitOffset = 22, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_23, bitOffset = 23, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_24, bitOffset = 24, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_25, bitOffset = 25, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_26, bitOffset = 26, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_27, bitOffset = 27, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_28, bitOffset = 28, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_29, bitOffset = 29, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_30, bitOffset = 30, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareField(peripheralName = ITM, registerName = ITM_TER, fieldName = STIMENA_31, bitOffset = 31, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Stimulus enable")
declareRegister(peripheralName = ITM, registerName = ITM_TPR, addressOffset = 0xE40'u32, readAccess = true, writeAccess = true, registerDesc = "Controls which stimulus ports can be accessed by unprivileged code")
declareField(peripheralName = ITM, registerName = ITM_TPR, fieldName = PRIVMASK, bitOffset = 0, bitWidth = 32, readAccess = true, writeAccess = true, fieldDesc = "Privilege mask")
